version: "3"
services:
    nginx:
        image: cward999/nginx:kube
        ports:
            - "80:80"
            - "81:81"
    streamlit:
        image: cward999/streamlit:kube
        expose:
            - 8501
    cellxgene:
        image: cward999/cellxgene-vip-gateway:latest
        expose:
            - 3838
