version: "3.9"
services:
    nginx:
        build: docker/nginx
        ports:
            - "8082:8082"
            - "8081:8081"
    streamlit:
        build: docker/streamlit
    cellxgene:
        image: cward999/cellxgene-vip-gateway:latest
